import Head from "next/head";
import Navbar from "../components/Navbar";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { BASE_URL } from "../constant/config";
import Table from "../components/Table/Table";
import { TableType } from "../config/type";
import { useState } from "react";
import TablePopup from "../components/Table/TablePopup";

export default function Home({
  tables,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const [popupOpen, setPopupOpen] = useState<string | null>(null);
  const [selectedTable, setSelectedTable] = useState<TableType | null>(null);

  return (
    <>
      <Head>
        <title>FC-POS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex bg-[#002A53] w-screen h-screen ">
        <div>
          <Navbar />
        </div>
        <div className="relative w-full flex flex-wrap justify-evenly items-center">
          {popupOpen && (
            <div className="flex flex-col justify-center absolute top-1/2 left-1/2 w-1/2 h-1/3 -translate-x-1/2 -translate-y-1/2 bg-gray-300 p-10 rounded-lg">
              <TablePopup
                selectedTable={selectedTable}
                setPopupOpen={setPopupOpen}
              />
            </div>
          )}

          {tables &&
            tables
              .sort((a, b) => a.order - b.order)
              .map((table) => (
                <Table
                  key={table.id}
                  table={table}
                  setSelectedTable={setSelectedTable}
                  setPopupOpen={setPopupOpen}
                />
              ))}
        </div>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  tables: TableType[];
}> = async () => {
  console.log(BASE_URL)
  const result = await fetch(`${BASE_URL}/api/table/table`);
  const tables = await result.json();

  return {
    props: {
      tables,
    },
  };
};
