import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>FC-POS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex bg-[#002A53] w-screen h-screen ">
        <div>
          <Navbar />
        </div>
        <div>
          <h1>FC POS</h1>
        </div>
      </div>
    </>
  );
}
