import Head from "next/head";
import Navbar from "../components/Navbar";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { BASE_URL } from "./constant/config";
import Table from "../components/Table/Table";

export default function Home({
  tables,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>FC-POS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex bg-[#002A53] w-screen h-screen ">
        <div>
          <Navbar />
        </div>
        <div className="w-full flex flex-wrap justify-evenly items-center">
          {tables && tables.map((table) => <Table table={table} />)}
        </div>
      </div>
    </>
  );
}

interface TableType {
  id: string;
  name: string;
  capacity: number;
  location: string;
  isParticipated: false;
}

export const getServerSideProps: GetServerSideProps<{
  tables: TableType[];
}> = async () => {
  const result = await fetch(`${BASE_URL}/api/table/table`);
  const tables = await result.json();

  return {
    props: {
      tables,
    },
  };
};
